### ISSUE TITLE
Samsung Galaxy A3 chrome svgs not working on homepage.

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#110]
Should there be a fallback?

**Comment by timswalling** [comment]
@alfraser86 SVGs should work in Android 3 and above, so it's likely whatever is causing that issue is either problem with the SVG itself or the way it's been positioned.

Can you please provide a screenshot and let me know which Android OS you're running?

**Comment by alfraser86** [comment]
@timswalling think I spotted what is causing this.

**Comment by alfraser86** [comment]
Almost certain this is now fixed
