### ISSUE TITLE
`cta--extension` pseudo-element styling is incorrect

### ISSUE THREAD

**Issue by timswalling** [wellcometrust/upd#118]
The styling of the filetype pseudo-elements should have reversed text on a semi-transparent lozenge:
![image](https://cloud.githubusercontent.com/assets/10677793/24696327/0425f44e-19e1-11e7-9f8d-131cbd369d93.png)

**Comment by alfraser86** [comment]
@timswalling which page is this on?

**Comment by timswalling** [comment]
@alfraser86 I'm not sure: it was flagged by our designer, but I don't know if he was referring to the Drupal build or the pattern library. Either way, it's wrong in the pattern library (it's a CSS issue), so I'll update.
