### ISSUE TITLE
Home page main image reported as tiny on ie11

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#124]
@timswalling This could well be a markup thing but I can't spot it. Would you mind having a quick look? Thanks https://understandingpatientdata.org.uk/

**Comment by timswalling** [comment]
@alfraser86 it's due to the way IE calculates SVG image dimensions. In order to make sure the sizing is bulletproof, I've made changes to the SVG itself, the CSS and the markup.

This will also ensure that the background image is sized appropriately before the illustration loads.
