### ISSUE TITLE
Search updated to do full text search on all pages

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#141]
Search functionality currently only searches certain fields. Full text search for all pages is a priority.

As part of this moving to a different search engine could be worth doing. We are set up to use Solr but could also move to hosted Elastic search.

**Comment by njcameron** [comment]
"Site wide" search should search through the body of all content

**Comment by njcameron** [comment]
- index text of taxonomy term / meta data
- ensure news / about us / basic pages / landing (tile) pages are indexed and displayed in results
- partial words
- autocomplete?
