### ISSUE TITLE
Caption/title functionality needs to be added for images

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#143]
Needs details: But I think some images need to be able to have captions displayed.

Original bug was reported as Alt text not displaying.

**Comment by njcameron** [comment]
Show alt text + title text on ALL content types / logos / images etc

**Comment by njcameron** [comment]
- Home
-- testimonial (no alt, no title)
-- case study (alt, no title)
- About us
-- meet the team  (alt, no title)
-- governance  (alt, no title)
-- funding / supporters (alt, no title)

**Comment by njcameron** [comment]
@alfraser86 the title attribute has been disabled on all image field settings, this is recommended by drupal. Seems like best practice is to not use the title attribute on anything:

https://www.w3.org/TR/html/dom.html#the-title-attribute
https://www.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/

When you hover over an image only the title is displayed not the alt. I think this is where the confusion is coming from.

**Comment by alfraser86** [comment]
@njcameron cool, lets just close this ticket then.
