### ISSUE TITLE
Case studies/case study landing page enhancements

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#145]
- [x] Add more filters (e.g. type of user, geographical area, 'risk factor' eg smoking, pollution, obesity etc)  
- [x]	The search function pulls up any word in the summary, but nothing from the body of text –  can we make the whole body of the case study searchable?  #141 
- [x]	It would be good to be able to add search terms to the case studies when the phrase doesn't appear in the text at all (e.g. 'pharmaceutical company' for a case study funded by AstraZeneca). We could add a feature for editors to add extra key words, e.g. for synonyms, acronyms etc.

**Comment by alfraser86** [comment]
- Add in taxonomies for type of user, geographical area.
- create facets for those taxonomies and add to case studies landing page.

**Comment by njcameron** [comment]
to do next: add keywords.
