### ISSUE TITLE
Look at doing an SEO audit and making some improvements.

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#156]
How do we improved our search-ablity? When you google 'patient data' and 'understanding patient data' we come too far down list!

This needs testing as I think UPD is doing quite well SEO wise now.

**Comment by alfraser86** [comment]
datasaveslives an important hashtag

**Comment by njcameron** [comment]
todo:

-home / general
-- add meta description
-- add keywords
-- add sitemap
-- fix alt tag testimonial
-- Facebook OG image
-- add twitter card for home + case study

**Comment by njcameron** [comment]
all config in place, waiting on some text from UPD team
