### ISSUE TITLE
Check designs to see if download boxes are styled correctly.

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#160]
https://understandingpatientdata.org.uk/what-does-anonymised-mean

**Comment by njcameron** [comment]
@alfraser86 where can I find the designs for UPD?

**Comment by alfraser86** [comment]
apologies for not giving you this immediately. https://projects.invisionapp.com/share/HAAPK56GD#/screens/224231197

**Comment by njcameron** [comment]
also fix CTA padding on download box http://upd.master.wt-stage2.codeenigma.net/what-are-best-words-use-when-talking-about-data

**Comment by njcameron** [comment]
@alfraser86 There is no design for multiple boxes, so I added some margin so they don't pile up on each other.

**Design**
![screen shot 2017-08-16 at 13 49 23](https://user-images.githubusercontent.com/1101879/29363941-be48c7a0-8289-11e7-89f5-dbcebea6a26f.png)

**Old site**
![screen shot 2017-08-16 at 13 50 21](https://user-images.githubusercontent.com/1101879/29363974-e4da99de-8289-11e7-8841-415b121666ba.png)

**New site**
![screen shot 2017-08-16 at 13 50 03](https://user-images.githubusercontent.com/1101879/29363977-e857ddf6-8289-11e7-890b-6e5da356f61d.png)

**Comment by alfraser86** [comment]
Cool if the UPD bunch are happy that looks good to me.
