### ISSUE TITLE
search for "anonymised" returns no results (US eng?)

### ISSUE THREAD

**Issue by njcameron** [wellcometrust/upd#176]

**Comment by njcameron** [comment]
https://wt-upd-master.codeenigma.net/search?query=anonymized

**Comment by njcameron** [comment]
@wellingk could you push this over to code enigma?

It should be a 2 letter change in the Apache Solr config file, but I'm not entirely sure where the change should happen.

**Comment by wellingk** [comment]
Sorry only just found this!  Ticket raised https://redmine.codeenigma.net/issues/27886

**Comment by wellingk** [comment]
@njcameron this is fixed now, if happy please close off the ticket.  😄

**Comment by njcameron** [comment]
works great thanks @wellingk !
