### ISSUE TITLE
Edit settings.php on staging and live to contain solr config

### ISSUE THREAD

**Issue by njcameron** [wellcometrust/upd#179]

**Comment by njcameron** [comment]
@wellingk Could you add this to stage and prod settings.php pls.

NB we should have a different core for prod and stage.

`$config['search_api.server.local_solr'] = [
  'backend_config' => [
    'connector_config' => [
      'host' => '172.30.0.21',
      'path' => '/solr',
      'core' => 'upd',
      'port' => '9191',
    ],
  ],
];`

**Comment by wellingk** [comment]
Cant create another core. :-(  Dont have permissions.  Requested this in #25908 on Redmine.  Hopefully Adrian will do that today.

**Comment by njcameron** [comment]
👍 

Can you do the settings.php on staging? That'll make deployment much easier

**Comment by wellingk** [comment]
Ignore that
I have managed the new core
elevated to root and was away

**Comment by wellingk** [comment]
Onto settings.php

**Comment by wellingk** [comment]
Done on both environments with the settings.php file

 NEW core or production is called prod_upd

**Comment by njcameron** [comment]
brill, thanks @wellingk
