### ISSUE TITLE
Newsletter subscription

### ISSUE THREAD

**Issue by pm98zz-c** [wellcometrust/upd#43]
The newsletter form in the footer does nothing. At minimal, it should send an email to a maillist service.

**Comment by alfraser86** [comment]
@pm98zz-c At the moment this isn't set up so for launch is being superseded by #52 but maybe we should sort something on thursday/friday

**Comment by njcameron** [comment]
@alfraser86 Is there any existing code / config for this?

**Comment by alfraser86** [comment]
@njcameron I believe there is a form that is hidden in the background. Not sure how. i can have a look.

**Comment by njcameron** [comment]
@alfraser86 there is this:

https://github.com/wellcometrust/upd/blob/master/www/themes/upd/templates/region/region--footer.html.twig#L55

but it looks like placeholder HTML, doesn't seem to be hooked up to any JS for subscribing

**Comment by njcameron** [comment]
todo

- [ ] Create mailchimp list with correct fields
- [ ] Create embeded form
- [ ] Theme form
