### ISSUE TITLE
The header is broken in FF

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#44]
http://patterns.wellcome-s3.org/upd/components/preview/site-header.html

**Comment by timswalling** [comment]
@alfraser86 this appears to be a duplicate of #37 - the header navigation was positioned below the main nav bar instead of flush with the top. Are you happy for me to close this, or is there another issue?

**Comment by alfraser86** [comment]
@timswalling go for it. Happy for you to manage your own Issues however is useful for you.
