### ISSUE TITLE
New standalone page

### ISSUE THREAD

**Issue by pm98zz-c** [wellcometrust/upd#74]
http://patterns.wellcome-s3.org/upd/components/detail/news-article-template.html

**Comment by pm98zz-c** [comment]
Related news behavior TBD

**Comment by alfraser86** [comment]
@pm98zz-c @miss-vija Related news should just be set by the content editor. They may want this to change at some point, but this is the functionality for go live.

**Comment by alfraser86** [comment]
@miss-vija Think this is done now so closing.
