### ISSUE TITLE
[Mobile] Extra left padding on homepagegrid--center

### ISSUE THREAD

**Issue by sonnybaker** [wellcometrust/upd#85]
Looks like triptych on the homepage is being nudged off centre by about 10px when stacking

**Comment by timswalling** [comment]
@alfraser86 It looks like the grid markup used is from an old version of the pattern - it doesn't apply the `gutter` classes used in the [pattern library](http://patterns.wellcome-s3.org/upd/components/preview/home.html).

**Comment by alfraser86** [comment]
@miss-vija @pm98zz-c Can you check markup on the homepage against the pattern lib. Thanks

**Comment by alfraser86** [comment]
Done
