### ISSUE TITLE
Clicking on the search button should place the cursor in the search box.

### ISSUE THREAD

**Issue by alfraser86** [wellcometrust/upd#91]
When I click the site-wide search button, the cursor isn’t placed in the search box so I started typing without the field being filled in. Currently users have to double click. I think this should happen in one click.

**Comment by timswalling** [comment]
@alfraser86 I can reproduce this issue in Chrome, but not in other browsers. Can you confirm that Chrome is the only affected browser?

**Comment by alfraser86** [comment]
It was tested on chrome
